

services:
  vite-dev:
    build: .
    ports:
      - "9999:9999"  # Allow a range since Vite may switch ports
    volumes:
      - .:/app
      - /app/node_modules     # Prevent host node_modules overwrite
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true   # fallback to polling for file changes
      - CHOKIDAR_INTERVAL=100      # (optional) poll every 100ms